openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /api/v1/users/current/:
    get:
      responses:
        '200':
          description: Get current user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /api/v1/tools/:
    get:
      responses:
        '200':
          description: Get tools
          content:
            application/json:
              schema:
                $ref: 'openapi-schema-split-datastructures.yaml#/ToolsList'
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          example: 1
        first_name:
          type: string
          example: John
        last_name:
          type: string
          example: Smith
