name: publish package to pypi

#on:
#  release:
#    types: [published]

on: push

jobs:
  build-and-publish:
    name: Build and publish
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
#      - name: Build and publish
#        run: |
#          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
#          poetry publish --build --no-interaction
      - run: cat pyproject.toml
      - name: Edit configuration to push django-swagger-tester
        run: |
          sed -i '' 's/name = "django-openapi-tester"/name = "django-swagger-tester"/' pyproject.toml
          sed -i '' 's/docs\/pypi\/README.rst/docs\/pypi\/OLD_README.rst/' pyproject.toml
      - run: cat pyproject.toml
