name: publish package to test-pypi and pypi

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Install dependencies
        run: |
          python -m poetry install
      - name: Build and publish
        run: |
          python -m poetry publish --build --pasword ${{ secrets.PYPI_TOKEN }} --no-interaction
