name: publish package to test-pypi and pypi

on:
  push
#  release:
#    types: [published]

jobs:
  build-and-publish:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install
        uses: abatilo/actions-poetry@v1.5.0
        with:
          python_version: 3.8
          poetry_version: 1.0.5
          working_directory: .  # <-- default
          args: install
      - name: Run pytest
        uses: abatilo/actions-poetry@v1.5.0
        with:
          python_version: 3.8
          poetry_version: 1.0.5
          working_directory: .  # <-- default
          args: run python -m pytest --cov=django_swagger_tester --verbose --color=yes  --assert=plain --cov-fail-under=95
      - name: Build and publish to pypi
        uses: abatilo/actions-poetry@v1.5.0
        with:
          python_version: 3.8
          poetry_version: 1.0.5
          working_directory: .  # <-- default
          args: publish --build --password ${{ secrets.PYPI_TOKEN }} --no-interaction
