name: test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - uses: actions/cache@v2
        id: cache-venv
        with:
          path: .venv
          key: venv-0  # increment to reset
      - run: |
          pip install virtualenv
          virtualenv .venv
          source .venv/bin/activate
          pip install pre-commit
        if: steps.cache-venv.outputs.cache-hit != 'true'
      - uses: actions/cache@v2
        id: pre-commit-cache
        with:
          path: ~/.cache/pre-commit
          key: key-0
      - run: |
          source .venv/bin/activate
          pre-commit run --all-files

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.7", "3.8" , "3.9", "3.10" ]
        django-version: [ "3.0", "3.1", "3.2", "4.0" ]
        exclude:
          # Django v4 drops Python 3.6, and 3.7 support
          - django-version: 4.0
            python-version: 3.7
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python-version }}"
      - uses: actions/cache@v2
        id: poetry-cache
        with:
          path: ~/.local
          key: key-3
      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false
      - uses: actions/cache@v2
        id: cache-venv
        with:
          path: .venv
          key: ${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}-2
      - run: |
          pip install virtualenv
          virtualenv .venv
          source .venv/bin/activate
          pip install pip setuptools wheel -U
          poetry install --no-interaction --no-root
        if: steps.cache-venv.outputs.cache-hit != 'true'
      - name: Install django version
        run: |
          source .venv/bin/activate
          pip install "Django==${{ matrix.django-version }}"
      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest --cov=. --cov-report xml --cov-report term-missing
      - name: Archive coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage-xml
          path: coverage.xml
        if: matrix.python-version == '3.10' && matrix.django-version == '4.0'
  coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get coverage
        uses: actions/download-artifact@v2
        with:
          name: coverage-xml
      - uses: codecov/codecov-action@v2
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Fix coverage file for sonarcloud
        run: |
          sed -i "s/<source>\/home\/runner\/work\/drf-openapi-tester\//<source>/g" coverage.xml
      - uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
